name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  swift:
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build
    - name: Run tests
      run: swift test
