name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    name: macOS
    strategy:
      matrix:
        xcode: ['16.1']
        config: ['debug', 'release']
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Run ${{ matrix.config }} tests
      run: swift test -c ${{ matrix.config }} --enable-code-coverage
    - name: Generate coverage report
      run: xcrun llvm-cov export -format="lcov" .build/debug/HTTPTests.xctest/Contents/MacOS/HTTPTests -instr-profile .build/debug/codecov/default.profdata > info.lcov
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        files: info.lcov
        token: ${{ secrets.CODECOV_TOKEN }}

  linux:
    name: Linux
    strategy:
      matrix:
        swift:
          - '6.0'
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: swift build

  compatibility:
    name: Compatibility
    strategy:
      matrix:
        xcode: ['15.2']
        config: ['debug', 'release']
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run ${{ matrix.config }} tests
        run: swift build -c ${{ matrix.config }}
